### ISSUE TITLE
Consider adding some sample datasets

### ISSUE THREAD

**Issue by adamltyson** [galizia-lab/pyview#20]
Hi, 

RE: [reviewing this paper for JOSS](https://github.com/openjournals/joss-reviews/issues/4936).

I've got the software running now on my machine. I might have missed a link somewhere, but I couldn't see a link to any sample data in the correct format/structure.

It would be very helpful to test the software, particularly for potential new users, if there was a link to sample data. Ideally this could be fetched from within the GUI.

Thanks,
Adam

**Comment by ajkswamy** [comment]
Hi Adam

I have added a section "Exploring PyView using Example datasets" to the page [Getting Started](https://github.com/galizia-lab/pyview/wiki/Getting-Started) of the wiki. Please download the example datasets and try our GUI/scripting workflows outlined on the same page. Let us know if you face any problems/issues!

Thanks!

Sincerely
Ajay

**Comment by adamltyson** [comment]
Thanks Ajay,

I'm trying to review this software from a users point of view, but even with this sample data it's hard to know where to begin. I think an introductory, step by step tutorial (see https://github.com/galizia-lab/pyview/issues/21) would be very useful. 

Adam
