### ISSUE TITLE
`failed to open iris` error

### ISSUE THREAD

**Issue by adamltyson** [galizia-lab/pyview#22]
When installing the software as per the instructions on a new Ubuntu 22.04 machine, I get the following error:

```
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
```

This appears to be fixed with `conda install -c conda-forge libstdcxx-ng`

I don't know how important this is, but it may be worth adding to the docs.

**Comment by galizia** [comment]
fantastic, thank you for the help!

*******************
Prof. Dr. Giovanni Galizia
Direktor Zukunftskolleg
Lehrstuhl Neurobiologie 
Permanent Fellow Wissenschaftskolleg zu Berlin
 
***@***.***
http://neuro.uni.kn
*****************************

**Comment by ajkswamy** [comment]
Thanks @adamltyson for testing and the suggestion. `libstdcxx-ng` is only available for linux. Nonetheless, it is indispensable in some cases, for example, when the linux machine has no C compiler installed. #33 creates two separate conda env files: one for linux with `libstdcxx-ng` as a dependency  and another for mac/win without.
