### ISSUE TITLE
LSM confocal files 

### ISSUE THREAD

**Issue by IngaPetelski** [galizia-lab/pyview#4]
Hey Ajay, is it possible to analyze lsm. confocal files in view? LE load experiment does not seem to work. The data is in /Volumes/AG_Galizia/02_EXCHANGE/Inga-Imaging/Ajay 
Thanks for your support, Inga

**Comment by ajkswamy** [comment]
Hi Inga. Yes it is possible. Here are some steps I would recommend:

1. Please create a sample tree according to this [guide](https://github.com/galizia-lab/pyview/wiki/Recommended-folder-structure)
2. For every animal, create a folder within "data" and paste the folder "images" and the MDB file into this newly created folder.
3. Create a measurement list for the data using this [guide](https://github.com/galizia-lab/pyview/wiki/Creating-measurement-lists). Please note that the value of "LE_loadExp" for Zeiss LSM files is 20.
4. You are now ready to visualize your data in VIEW and create tapestries, movies or export data to CSV or MAT files!

I will close this issue now, but please feel free to reopen it if you have more questions or issues regarding this!

**Comment by IngaPetelski** [comment]
Great thanks Ajay it works!
